apiVersion: apps/v1
kind: Deployment
metadata:
  name: env0-nfs-server
  namespace: env0-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      role: env0-nfs-server
  template:
    metadata:
      labels:
        role: env0-nfs-server
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-central1-a__us-central1-b
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /data
            name: nfs-pvc
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: env0-pvc-for-nfs-server         
