apiVersion: v1
kind: Service
metadata:
  name: env0-nfs-server
  namespace: env0-agent
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: env0-nfs-server
